### ISSUE TITLE
Letter month mapping is wrong

### ISSUE THREAD

**Issue by salvatoreboemia** [TheInkedEngineer/Spritz#2]
Hi, I noticed an error in mapping the months with the letters. 

Comparing with the table on wikipedia, in fact, they are incorrect.

https://it.wikipedia.org/wiki/Codice_fiscale#Luogo_di_nascita

I tried to change them and fix (Transformers.swift), but in any case when calculating people born in August, October etc, I have different letters and consequently also the final check character. (if you want to write to me I am Italian. I can also write to you by email if you want)

Is a pod fix possible? Also is there a way to calculate the reverse too? Thanks so much

**Comment by TheInkedEngineer** [comment]
@salvatoreboemia this should fix it :)
https://github.com/TheInkedEngineer/Spritz/pull/3

Feel free to have a look if you want, before I merge it and release it.

As for the reverse, feel free to open a PR.
I did not include it because it's not something usually requested. Plus it can only be applied to certain fields. There is no way to get the user name or last name for instance from the code itself.

**Comment by TheInkedEngineer** [comment]
This has been addressed and solved in version 1.0.1

Please update your pod.

I will address your other concerns sent via email in a separate way.
